// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/gcp/gcp.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "google.golang.org/api/compute/v1"
)

// MockGCPClient is a mock of GCPClient interface.
type MockGCPClient struct {
	ctrl     *gomock.Controller
	recorder *MockGCPClientMockRecorder
}

// MockGCPClientMockRecorder is the mock recorder for MockGCPClient.
type MockGCPClientMockRecorder struct {
	mock *MockGCPClient
}

// NewMockGCPClient creates a new mock instance.
func NewMockGCPClient(ctrl *gomock.Controller) *MockGCPClient {
	mock := &MockGCPClient{ctrl: ctrl}
	mock.recorder = &MockGCPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCPClient) EXPECT() *MockGCPClientMockRecorder {
	return m.recorder
}

// CreateInstance mocks base method.
func (m *MockGCPClient) CreateInstance(projectID, zone string, instance *v1.Instance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", projectID, zone, instance)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockGCPClientMockRecorder) CreateInstance(projectID, zone, instance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockGCPClient)(nil).CreateInstance), projectID, zone, instance)
}

// GetInstance mocks base method.
func (m *MockGCPClient) GetInstance(projectID, zone, instanceName string) (v1.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", projectID, zone, instanceName)
	ret0, _ := ret[0].(v1.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockGCPClientMockRecorder) GetInstance(projectID, zone, instanceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockGCPClient)(nil).GetInstance), projectID, zone, instanceName)
}

// GetInstancePorts mocks base method.
func (m *MockGCPClient) GetInstancePorts(projectID, zone, instanceName string) (*v1.SerialPortOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstancePorts", projectID, zone, instanceName)
	ret0, _ := ret[0].(*v1.SerialPortOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstancePorts indicates an expected call of GetInstancePorts.
func (mr *MockGCPClientMockRecorder) GetInstancePorts(projectID, zone, instanceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstancePorts", reflect.TypeOf((*MockGCPClient)(nil).GetInstancePorts), projectID, zone, instanceName)
}

// ListMachineTypes mocks base method.
func (m *MockGCPClient) ListMachineTypes(projectID, zone string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMachineTypes", projectID, zone)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMachineTypes indicates an expected call of ListMachineTypes.
func (mr *MockGCPClientMockRecorder) ListMachineTypes(projectID, zone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMachineTypes", reflect.TypeOf((*MockGCPClient)(nil).ListMachineTypes), projectID, zone)
}

// SetInstanceLabels mocks base method.
func (m *MockGCPClient) SetInstanceLabels(projectID, zone, instanceName string, labelReq *v1.InstancesSetLabelsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInstanceLabels", projectID, zone, instanceName, labelReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInstanceLabels indicates an expected call of SetInstanceLabels.
func (mr *MockGCPClientMockRecorder) SetInstanceLabels(projectID, zone, instanceName, labelReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInstanceLabels", reflect.TypeOf((*MockGCPClient)(nil).SetInstanceLabels), projectID, zone, instanceName, labelReq)
}

// TerminateComputeServiceInstance mocks base method.
func (m *MockGCPClient) TerminateComputeServiceInstance(projectID, zone, instanceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateComputeServiceInstance", projectID, zone, instanceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateComputeServiceInstance indicates an expected call of TerminateComputeServiceInstance.
func (mr *MockGCPClientMockRecorder) TerminateComputeServiceInstance(projectID, zone, instanceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateComputeServiceInstance", reflect.TypeOf((*MockGCPClient)(nil).TerminateComputeServiceInstance), projectID, zone, instanceName)
}
